# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: mysql
  database: server_site
  username: root
  password:
  encoding: utf8
  host: localhost

